name: R Check
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up R
      uses: ./.github/actions/my-action
      with:
        r-version: '4.0.3'
    - name: Install dependencies
      run: |
        install.packages("devtools")
        devtools::install_deps(dependencies = TRUE)
    - name: Check
      run: |
        R CMD build .
        R CMD check *tar.gz --as-cran
