name: R Package Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: R Install Check
      uses: r-lib/actions/setup-r@v1
      with:
        version: "4.1.1"
    - name: Install Package Dependencies
      run: |
        R -e "install.packages(c('devtools', 'remotes', 'testthat', 'roxygen2', 'covr', 'pkgdown', 'rmarkdown', 'knitr'), dependencies = TRUE)"
    - name: Check Package
      run: |
        R -e "devtools::check()"
